name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OWNER_LC: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/lit-smp-bot:latest
